name: destroy infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"

jobs:
  destroy:
    name: Destroy Azure Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the branch"

        uses: "actions/checkout@v5"

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDS}}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: "Initialize Terraform"
        working-directory: ./infra
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.STORAGE_RG }}" \
            -backend-config="storage_account_name=${{ secrets.STORAGE_AC }}" \
            -backend-config="container_name=${{ secrets.BLOB_CON }}" \
            -backend-config="key=${{ secrets.keytf }}"

      - name: "destroy all plan"
        working-directory: ./infra
        run: terraform plan -destroy -lock=false

      - name: "destroy all "
        working-directory: ./infra
        run: terraform destroy -auto-approve -lock=false || terraform destroy -auto-approve -lock=false || terraform destroy -auto-approve -lock=false
